export function codeDrawer(listaDeCodigos: string[]): string {
   const indiceSorteado = Math.floor(Math.random() * listaDeCodigos.length);
   return listaDeCodigos[indiceSorteado];
}

export const listaDeCodigosGtaS = [
   "LXGIWYL",
   "KJKSZPJ",
   "UZUMYMW",
   "NCSGDAG",
   "WANRLTW",
   "JYSDSOD",
   "OGXSDAG",
   "EHIBXQS",
   "BTCDBCB",
   "KVGYZQK",
   "LFGMHAL",
   "IAVENJQ",
   "BEKKNQV",
   "MUNASEF",
   "BAGUVIX",
   "AGBDLCID",
   "AIWPRTON",
   "AMOMHRER",
   "AQTBCODX",
   "CQZIJMB",
   "EEGCYXT",
   "JUMPJET",
   "PDNEJOH",
   "VPJTQWV",
   "URKQSRK",
   "YECGAA",
   "AIYPWZQP",
   "AUIFRVQS",
   "ALNSFMZO",
];

export const listaDeCodigosGtaV = [
   "CATCHME",
   "SKYDIVE",
   "FLOATER",
   "LIQUOR",
   "SLOWMO",
   "SKYFALL",
   "TURTLE",
   "FUGITIVE",
   "LAWYERUP",
   "HOTHANDS",
   "POWERUP",
   "DEADEYE",
   "BANDIT",
   "TRASHED",
   "SNOWDAY",
   "BUZZOFF",
   "COMET",
   "ROCKET",
   "OFFROAD",
   "RAPIDGT",
   "VINEWOOD",
];
